// This file was automatically generated by the afbd tool.
// https://github.com/Functional-Bus-Description-Language/afbd

#include "afbd.h"

int afbd_apb_test_write_read_reg_read(afbd_iface_t * const iface, uint32_t * const data)
{
	return iface->read(iface, 0, data);
};

int afbd_apb_test_write_read_reg_write(afbd_iface_t * const iface, uint32_t const data)
{
	return iface->write(iface, 0, data);
};

