// This file was automatically generated by the afbd tool.
// https://github.com/Functional-Bus-Description-Language/afbd

#ifndef _AFBD_apb_test_H_
#define _AFBD_apb_test_H_

#define AFBD_apb_test_OWN_ALIGNED_SIZE 1024
#define AFBD_apb_test_ALIGNED_SIZE 1024

#include "afbd.h"

int afbd_apb_test_write_read_reg_read(afbd_iface_t * const iface, uint32_t * const data);
int afbd_apb_test_write_read_reg_write(afbd_iface_t * const iface, uint32_t const data);

#endif // _AFBD_apb_test_H_
