// This file was automatically generated by the afbd tool.
// https://github.com/Functional-Bus-Description-Language/afbd

#ifndef _AFBD_gpio_H_
#define _AFBD_gpio_H_

#include "afbd.h"

int afbd_gpio_switches_read(afbd_iface_t * const iface, uint8_t * const data);

int afbd_gpio_leds_read(afbd_iface_t * const iface, uint8_t * const data);
int afbd_gpio_leds_write(afbd_iface_t * const iface, uint8_t const data);

#endif // _AFBD_gpio_H_
