// This file was automatically generated by the afbd tool.
// https://github.com/Functional-Bus-Description-Language/afbd

#ifndef _AFBD_MMAP_IFACE_H_
#define _AFBD_MMAP_IFACE_H_

#if defined(__KERNEL__)
	#include <linux/types.h>
#else
	#include <stddef.h>
	#include <stdint.h>
#endif

#include "afbd.h"

// Initializes are returns afbd interface.
// iomem is a pointer to the memory-mapped IO (registers).
afbd_iface_t afbd_linux_mmap_iface(void *const iomem);

#endif // _AFBD_MMAP_IFACE_H_
