#!/usr/bin/env python3

import datetime
import json
import os
import string
import sys

M_GP0_ADDR = 0x40000000

dts = string.Template(
    """// This file was automatically generated by the $script_name script.
/dts-v1/;
/plugin/;

/ {
	#address-cells = <1>;
	#size-cells = <1>;

	gpio: gpio@$gpio_addr {
		compatible = "gpio";
		reg = <0x$gpio_addr $gpio_size>;
	};
};"""
)


def get_subblock(block, name):
    for subblock in block["Subblocks"]:
        if subblock["Name"] == name:
            return subblock

        for subblk in subblock["Subblocks"]:
            sb = get_subblock(subblk, name)
            if sb != None:
                return sb

    return None


def get_block_size(blk):
    return blk["Sizes"]["Aligned"]


if len(sys.argv) != 2:
    raise Exception("expecting one argument, path to json registerification results")

# Load main bus description from the json registerification results
with open(sys.argv[1], "r", encoding="utf-8") as f:
    main = json.load(f)

gpio = get_subblock(main, "gpio")

data = {
    "script_name": os.path.basename(__file__),
    "gpio_addr": format(M_GP0_ADDR + 4 * gpio["AddrSpace"]["Start"], 'x'),
    "gpio_size": hex(4 * get_block_size(gpio)),
}

dts = dts.substitute(data)
print(dts)
