#!/usr/bin/env python3

import datetime
import json
import os
import string
import sys

M_GP0_ADDR = 0x40000000

dts = string.Template(
    """// This file was automatically generated by the $script_name script.
/dts-v1/;
/plugin/;

&amba {
	#address-cells = <1>;
	#size-cells = <1>;

	ex-uio@$main_addr {
		compatible = "generic-uio";
		reg = <0x$main_addr $main_size>;
	};

	ex-gpio@$gpio_addr {
		compatible = "ex-gpio";
		reg = <0x$gpio_addr $gpio_size>;
	};

	ex-timer-irq@$timer_addr {
		compatible = "ex-timer-irq";
		reg = <0x$timer_addr $timer_size>;
		interrupt-parent = <&intc>;
		interrupts = <0 59 1>; // 0: shared peripheral interrupt, 59: IRQ ID 91, 1: rising edge
	};
};"""
)


def get_block(block, name):
    if block["Name"] == name:
        return block

    if block["Subblocks"] is None:
        return None

    for subblock in block["Subblocks"]:
        if subblock["Name"] == name:
            return subblock

        for subblk in subblock["Subblocks"] or []:
            sb = get_block(subblk, name)
            if sb != None:
                return sb

    return None


def get_block_own_size(blk):
    return blk["Sizes"]["OwnAligned"]


if len(sys.argv) != 2:
    raise Exception("expecting one argument, path to json registerification results")

# Load main bus description from the json registerification results
with open(sys.argv[1], "r", encoding="utf-8") as f:
    main = json.load(f)

gpio = get_block(main, "gpio")
timer = get_block(main, "timer")

data = {
    "script_name": os.path.basename(__file__),
    "main_addr": format(M_GP0_ADDR + 4 * main["AddrSpace"]["Start"], 'x'),
    "main_size": hex(4 * get_block_own_size(main)),
    "gpio_addr": format(M_GP0_ADDR + 4 * gpio["AddrSpace"]["Start"], 'x'),
    "gpio_size": hex(4 * get_block_own_size(gpio)),
    "timer_addr": format(M_GP0_ADDR + 4 * timer["AddrSpace"]["Start"], 'x'),
    "timer_size": hex(4 * get_block_own_size(timer)),
}

dts = dts.substitute(data)
print(dts)
